apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  PROJECT_ID: "daring-keep-408013"
  LOCATION: "us-central1-a"
  CLUSTER_NAME: "app-backend-cluster"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-base-service
  namespace: default
  labels:
    app: python-base-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-base-service
  template:
    metadata:
      labels:
        app: python-base-service
    spec:
      containers:
        - name: python-base-service
          image: gcr.io/daring-keep-408013/github.com/finster-ai/services/python-base-service/python-base-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2048Mi
              cpu: 500m
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
            - name: FLASK_ENV
              value: "development"  # Set the desired environment here (e.g., development, production, local)
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: PROJECT_ID
            - name: LOCATION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: LOCATION
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: CLUSTER_NAME
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key
