app:
    secret_key: "prod_secret_key"
    debug: false
#    project_id: "daring-keep-408013"
#    location: "us-central1"
auth:
    domain: "dev-dev53al0gd7odyq5.us.auth0.com"
    audience: "https://auth-dev.finster.ai"
    algorithms: ["RS256"]
database:
    sql:
        uri: "DEVELOPMENT_DB_URL"
        pool_size: 20
        version: 1.1.4
    mongodb:
        uri: "mongodb+srv://finster-dev:3tLRNLbel7DCZCal@finster-dev.gixif.mongodb.net/?retryWrites=true&w=majority&appName=finster-dev"
        #        database: "MONGODB_DATABASE"
    redis:
        host: "redis-12997.c259.us-central1-2.gce.redns.redis-cloud.com"
        port: 12997
        password: 'dJ6czkdTtsTqWreLP4gRvT3VYydgIjaa'
pubsub:
    project_id: "daring-keep-408013"
    topic_id: "test-queue-dev"
    subscription_id: "test-queue-dev-sub"




